name: Update API Data

on:
  schedule:
    - cron: '*/40 * * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - env:
          COOKIE_API_URL: ${{ secrets.COOKIE_API_URL }}
          SOURCE_API_URL: ${{ secrets.SOURCE_API_URL }}
        run: |
          COOKIE=$(curl -s "$COOKIE_API_URL")
          curl -s "$SOURCE_API_URL" > source_api.json
          jq --arg cookie "$COOKIE" '.data |= map(.url |= . + "?" + $cookie)' source_api.json > rest_api.json

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rest_api.json
          git commit -m "update rest_api.json" || exit 0
          git push
